CustomizableWeaponry:addFireSound("CW_BLACKOPS3_QUICKSCOPE_FIRE", "weapons/blackops3/quickscope/wpn_sniper_short_fire.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_BLACKOPS3_QUICKSCOPE_FIRE_SUPPRESSED", "weapons/blackops3/quickscope/wpn_sniper_short_suppressed_fire.wav", 1, 70, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Magout", "weapons/blackops3/quickscope/fly_9000_mag_out_02.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Magin", "weapons/blackops3/quickscope/fly_9000_mag_in.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Bolt_Back", "weapons/blackops3/quickscope/fly_9000_bolt_back.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Bolt_Forward", "weapons/blackops3/quickscope/fly_9000_bolt_forward.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Spin", "weapons/blackops3/quickscope/fly_9000_spin.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Shell_In", "weapons/blackops3/quickscope/fly_9000_shell_in.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_QUICKSCOPE.Tap", "weapons/blackops3/quickscope/fly_9000_tap.wav")