CustomizableWeaponry:addFireSound("CW_BLACKOPS3_XR2_FIRE", "weapons/blackops3/xr2/wpn_xr2_fire_single.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_BLACKOPS3_XR2_FIRE_SUPPRESSED", "weapons/blackops3/xr2/wpn_xr2_fire_single_suppressed.wav", 1, 70, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Magout", "weapons/blackops3/xr2/fly_xr2_mag_out_00.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Magin", "weapons/blackops3/xr2/fly_xr2_mag_in_00.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Button", "weapons/blackops3/xr2/fly_xr2_button.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Wheel", "weapons/blackops3/xr2/fly_xr2_wheel_00.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Tap", "weapons/blackops3/xr2/fly_xr2_tap_00.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Bolt_Back", "weapons/blackops3/xr2/fly_xr2_bolt_back_00.wav")
CustomizableWeaponry:addReloadSound("Weapon_BLACKOPS3_XR2.Bolt_Forward", "weapons/blackops3/xr2/fly_xr2_bolt_forward_02.wav")